# Generated by Django 5.1.1 on 2024-10-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sobre', models.CharField(max_length=100)),
                ('imagem', models.ImageField(null=True, upload_to='static/')),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Noticia',
            },
        ),
    ]
