# Generated by Django 5.1.2 on 2024-11-01 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_noticia_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='criado_em',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='link',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='noticia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario_set', to='app.noticia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='sobre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
