# Generated by Django 5.1.2 on 2024-11-01 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_noticia_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoencaPraga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens/')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidade_se_sim', models.FloatField()),
                ('probabilidade_se_nao', models.FloatField()),
                ('doenca_praga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.doencapraga')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pergunta')),
            ],
        ),
        migrations.AddField(
            model_name='pergunta',
            name='doencas_pragas',
            field=models.ManyToManyField(related_name='perguntas', through='app.Resposta', to='app.doencapraga'),
        ),
    ]
