# Generated by Django 5.1.2 on 2024-11-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_doencapraga_pergunta_resposta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='doenca_praga',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='doencas_pragas',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='pergunta',
        ),
        migrations.DeleteModel(
            name='DoencaPraga',
        ),
        migrations.DeleteModel(
            name='Pergunta',
        ),
        migrations.DeleteModel(
            name='Resposta',
        ),
    ]
