# Generated by Django 5.0.7 on 2024-11-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
